import type { SiteContent } from "./types";
import { DRAWER_NAV_ITEMS, routes } from "@/lib/navigation";
import { defaultHeroBuilder } from "./hero-builder-defaults";
import { CULTURE_HOME_CONTENT, CULTURE_PAGE_STORY } from "./culture-content";
import { DEFAULT_ROOM_POLICIES } from "./room-helpers";

export const defaultContent: SiteContent = {
  hotel: {
    name: "Hotel Thamel Park",
    tagline: "Luxury Stay Experience in the Heart of Thamel, Kathmandu",
    description:
      "Experience refined comfort, elevated dining, wellness experiences, and exceptional hospitality in the heart of Kathmandu.",
    location: "Thamel, Kathmandu, Nepal",
    address: "Thamel, Kathmandu 44600, Nepal",
    phone: "+977-1-4412345",
    email: "reservations@hotelthamelpark.com",
    social: {
      facebook: "https://facebook.com/hotelthamelpark",
      instagram: "https://instagram.com/hotelthamelpark",
      twitter: "https://twitter.com/hotelthamelpark",
      tripadvisor: "https://tripadvisor.com/hotelthamelpark",
    },
  },
  header: {
    useLogo: false,
    showText: true,
    hideText: false,
    headerText: "HOTEL THAMEL PARK",
    logoSrc: "/media/logo/hotel-logo.png",
    logoSize: 48,
    height: 72,
    sticky: true,
    transparent: true,
    backgroundColor: "#FDFBF7",
    textColor: "#183426",
    showStars: false,
    phone: "+977-1-4412345",
    showPhone: true,
    bookButtonText: "Book Now",
    menuItems: [...DRAWER_NAV_ITEMS],
    overlayMenuItems: [],
  },
  hero: defaultHeroBuilder,
  homeSections: {
    hero: { enabled: true, order: 0 },
    welcome: { enabled: true, order: 1, eyebrow: "Welcome", title: "In the Heart of Thamel", description: "Outstanding hospitality in Kathmandu." },
    aboutPreview: { enabled: true, order: 2, eyebrow: "Heritage", title: "Authentic Cultural Experience", description: "Experience Nepali warmth and charm." },
    rooms: { enabled: true, order: 3, eyebrow: "Accommodations", title: "The Rooms", description: "Sanctuaries of refined comfort.", ctaText: "View All Rooms", ctaHref: routes.rooms },
    facilities: { enabled: true, order: 4, eyebrow: "Amenities", title: "World-Class Facilities", description: "Every detail curated for your comfort." },
    dining: { enabled: true, order: 5, eyebrow: "Culinary", title: "Dining Experiences", description: "From Korean cuisine to rooftop evenings." },
    spa: { enabled: true, order: 6, eyebrow: "Wellness", title: "Spa & Renewal", description: "Restore body, mind, and spirit." },
    meetingsEvents: { enabled: true, order: 6.5, eyebrow: "Events & Meetings", title: "Meetings & Events", description: "World-class event facilities with Himalayan backdrops." },
    exploreKathmandu: { enabled: true, order: 6.75, eyebrow: "Explore Kathmandu", title: "Sightseeing & Day Trips", description: "Private and group excursions to UNESCO sites and hidden gems." },
    gallery: { enabled: true, order: 7, eyebrow: "Visual Journey", title: "Moments of Elegance", description: "Discover our world of luxury." },
    testimonials: { enabled: true, order: 8, eyebrow: "Guest Voices", title: "Testimonials", description: "Stories from our distinguished guests." },
    cta: { enabled: true, order: 9, eyebrow: "Reservations", title: "Begin Your Journey", description: "Our concierge awaits your arrival.", ctaText: "Contact Us", ctaHref: routes.contact },
  },
  overview: {
    eyebrow: "Welcome",
    title: "In the Heart of Thamel, Outstanding Hospitality",
    content:
      "Hotel Thamel Park is a premium hotel located in the heart of Thamel, Kathmandu, offering comfortable rooms, fine dining, wellness experiences, and warm Nepalese hospitality.",
    backgroundTop: "#FAF6EE",
    backgroundBottom: "#0F2A22",
    headingColor: "#0F2420",
    bodyColor: "#5A6B60",
    goldColor: "#D4AF37",
    spacing: {
      sectionPaddingY: 88,
      sliderMaxHeight: 540,
    },
    slider: {
      autoPlay: true,
      loop: true,
      slideDurationMs: 5500,
      transitionSpeedMs: 900,
      showArrows: true,
      showDots: true,
      maxImages: 12,
      slides: [
        { id: "slide1", src: "/media/gallery/01.jpg", alt: "Hotel Thamel Park luxury pool", enabled: true, order: 0 },
        { id: "slide2", src: "/media/gallery/02.jpg", alt: "Premium hotel exterior", enabled: true, order: 1 },
        { id: "slide3", src: "/media/gallery/03.jpg", alt: "Fine dining experience", enabled: true, order: 2 },
        { id: "slide4", src: "/media/gallery/04.jpg", alt: "Elegant guest lounge", enabled: true, order: 3 },
      ],
    },
    galleryImages: [
      "/media/gallery/01.jpg",
      "/media/gallery/02.jpg",
      "/media/gallery/03.jpg",
      "/media/gallery/04.jpg",
    ],
    stats: [
      {
        id: "stat1",
        value: 20,
        suffix: "+",
        label: "Years of Hospitality",
        icon: "crown",
        enabled: true,
        order: 0,
        backgroundColor: "#0F2A22",
        textColor: "#D4AF37",
        borderColor: "#C8A145",
      },
      {
        id: "stat2",
        value: 84,
        suffix: "",
        label: "Luxury Rooms",
        icon: "bed",
        enabled: true,
        order: 1,
        backgroundColor: "#0F2A22",
        textColor: "#D4AF37",
        borderColor: "#C8A145",
      },
      {
        id: "stat3",
        value: 25,
        suffix: "K+",
        label: "Happy Guests",
        icon: "users",
        enabled: true,
        order: 2,
        backgroundColor: "#0F2A22",
        textColor: "#D4AF37",
        borderColor: "#C8A145",
      },
    ],
  },
  roomsSection: {
    eyebrow: "Accommodations",
    title: "The Rooms",
    description:
      "Each room is a sanctuary of refined comfort, designed for discerning travelers seeking the finest hospitality.",
    ctaText: "Discover All Rooms",
    ctaHref: routes.rooms,
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
  },
  experiences: [
    {
      id: "garden-restaurant",
      title: "Garden View & Korean Restaurant",
      content:
        "Garden View & Korean Restaurant offers an elegant dining experience where panoramic greenery meets the precision of Korean culinary artistry. Our chefs prepare authentic dishes using premium ingredients — from hand-cut sashimi to flame-kissed barbecue — served in a serene setting ideal for intimate dinners and distinguished gatherings.\n\nFrom sizzling tabletop grills to refined banchan presentations, every course is composed with care. The atmosphere balances soft lighting, natural textures, and attentive service — creating an occasion worthy of your stay in Kathmandu.\n\nWhether celebrating a milestone or hosting a private dinner, our team crafts bespoke menus and wine pairings that honour both Korean tradition and the cosmopolitan spirit of Thamel.",
      imageSrc: "/media/dining/korean-restaurant.jpg",
      imagePosition: "left",
      variant: "dining",
    },
    {
      id: "lobby-cafe",
      title: "Cafe in Lobby Area",
      content:
        "The lobby café is a quiet luxury pause — a place for morning espresso, afternoon meetings, and unhurried conversation. Premium beans, artisan pastries, and a curated tea selection are served in an atmosphere of understated elegance.\n\nWhether you are preparing for a day of exploration or returning from the city’s temples and markets, our café offers a refined interlude with impeccable service and warm Nepalese hospitality.",
      imageSrc: "/media/dining/lobby-cafe.jpg",
      imagePosition: "right",
      variant: "cafe",
    },
    {
      id: "sky-lounge",
      title: "Sky Lounge Restaurant & Bar",
      content:
        "Sky Lounge Restaurant & Bar elevates your evening with rooftop views, crafted cocktails, and a menu that celebrates global flavours with local soul. As the sun sets over Kathmandu, the terrace transforms into one of the city’s most atmospheric dining destinations.\n\nLive music evenings, curated wine selections, and a dedicated mixology programme ensure every visit feels celebratory — yet never hurried. Reserve your table for an unforgettable night above Thamel.",
      imageSrc: "/media/dining/skyz-lounge.jpg",
      imagePosition: "left",
      variant: "lounge",
    },
    {
      id: "spa-wellness",
      title: "Spa & Wellness",
      content:
        "Our spa and wellness sanctuary is a haven of restoration — blending Himalayan healing traditions with contemporary luxury therapies. Each treatment is tailored to renew body, mind, and spirit in an environment of absolute tranquillity.\n\nFrom therapeutic massage and steam rituals to bespoke wellness journeys, every experience is designed to complement your stay. Emerge refreshed, centred, and ready to embrace the cultural wonders of Kathmandu.\n\nPrivate treatment suites, aromatherapy baths, and couples' rituals draw on indigenous herbs and time-honoured techniques — delivered by therapists trained in both Eastern and Western wellness disciplines.",
      imageSrc: "/media/spa/wellness.jpg",
      imagePosition: "right",
      variant: "spa",
    },
  ],
  locationAdvantages: [
    { id: "thamel", title: "Thamel", distance: "Prime Location", icon: "MapPin" },
    { id: "airport", title: "Tribhuvan International Airport", distance: "6 KM", icon: "Plane" },
    { id: "pashupatinath", title: "Pashupatinath Temple", distance: "5 KM", icon: "Landmark" },
    { id: "swayambhunath", title: "Swayambhunath Stupa", distance: "3 KM", icon: "Church" },
    { id: "durbar", title: "Kathmandu Durbar Square", distance: "1.5 KM", icon: "Castle" },
    { id: "garden", title: "Garden of Dreams", distance: "400 M", icon: "Flower2" },
  ],
  culture: {
    eyebrow: "Nepali Heritage",
    title: "Authentic Cultural Experience",
    description:
      "Experience authentic Nepali culture, traditional hospitality, and the unique charm of Kathmandu while staying with us.",
    content: CULTURE_HOME_CONTENT,
    imageSrc: "/media/culture/nepali-culture.jpg",
    media: {
      type: "image",
      imageSrc: "/media/culture/nepali-culture.jpg",
      videoSrc: "",
      poster: "",
      alt: "Boudhanath Stupa at sunset in Kathmandu",
      caption: "Discover the soul of Nepal from the heart of Thamel",
    },
    circularImage: "/media/gallery/05.jpg",
    circularImageAlt: "Traditional Nepali cultural performance",
    badge: {
      enabled: true,
      number: "20+",
      emphasis: "20+ Years",
      description:
        "We have more than 20+ Years of experience in hospitality and cultural excellence.",
      iconSrc: "",
    },
    quote:
      "In Nepal, every courtyard holds a story, every temple a prayer, and every guest a blessing.",
    quoteAuthor: "Nepali Proverb",
    highlightsLabel: "Experience Highlights",
    ctaText: "Explore Cultural Experience",
    ctaHref: "/cultural-experience",
    ctaVisible: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    showMist: true,
    stats: [
      { id: "cs1", value: "7", label: "UNESCO Sites Nearby", icon: "Landmark", enabled: true, order: 0 },
      { id: "cs2", value: "2000+", label: "Years of Heritage", icon: "Clock", enabled: true, order: 1 },
      { id: "cs3", value: "50+", label: "Curated Experiences", icon: "Star", enabled: true, order: 2 },
    ],
    imageCards: [
      {
        id: "ic-dance",
        enabled: true,
        order: 0,
        label: "CULTURE",
        title: "Traditional Nepali Dance",
        description:
          "Witness vibrant folk performances celebrating centuries of Himalayan rhythm and ritual.",
        href: "/cultural-experience",
        media: {
          type: "image",
          imageSrc: "/media/gallery/05.jpg",
          videoSrc: "",
          poster: "",
          alt: "Traditional Nepali dance performance",
          caption: "Traditional Dance",
        },
      },
      {
        id: "ic-cuisine",
        enabled: true,
        order: 1,
        label: "CULINARY",
        title: "Local Cuisine Experience",
        description:
          "Savor authentic Newari and Nepali flavors guided by our cultural concierge.",
        href: "/cultural-experience",
        media: {
          type: "image",
          imageSrc: "/media/dining/korean-restaurant.jpg",
          videoSrc: "",
          poster: "",
          alt: "Local Nepali cuisine experience",
          caption: "Local Cuisine",
        },
      },
      {
        id: "ic-aarti",
        enabled: true,
        order: 2,
        label: "SPIRITUAL",
        title: "Temple Evening Aarti",
        description:
          "Join sacred evening ceremonies along the Bagmati with butter lamps and prayer.",
        href: "/cultural-experience",
        media: {
          type: "image",
          imageSrc: "/media/culture/nepali-culture.jpg",
          videoSrc: "",
          poster: "",
          alt: "Temple evening aarti ceremony",
          caption: "Temple Aarti",
        },
      },
    ],
    highlights: [
      {
        id: "h1",
        title: "Heritage Walks",
        description: "Private guided tours through UNESCO monuments and hidden courtyards.",
        icon: "Landmark",
        enabled: true,
        order: 0,
      },
      {
        id: "h2",
        title: "Local Cuisine",
        description: "Authentic Nepali flavors, home tastings, and market-to-table experiences.",
        icon: "UtensilsCrossed",
        enabled: true,
        order: 1,
      },
      {
        id: "h3",
        title: "Temple Visits",
        description: "Sacred ceremonies, evening aarti, and spiritual guidance.",
        icon: "Church",
        enabled: true,
        order: 2,
      },
      {
        id: "h4",
        title: "Festival Calendar",
        description: "Dashain, Tihar, Holi, and local jatra celebrations year-round.",
        icon: "Calendar",
        enabled: true,
        order: 3,
      },
    ],
    timeline: [
      {
        year: "Morning",
        title: "Temple & Heritage Walk",
        description: "Begin with Swayambhunath or Durbar Square at golden hour.",
      },
      {
        year: "Afternoon",
        title: "Artisan Quarter",
        description: "Visit Patan workshops for brass, thangka, and woodcarving.",
      },
      {
        year: "Evening",
        title: "Cultural Dining",
        description: "Newari feast or rooftop dinner with Himalayan views.",
      },
    ],
  },
  facilitiesSection: {
    eyebrow: "World-Class Amenities",
    title: "All the Essentials for a Refined Stay",
    description:
      "Every detail has been curated to deliver the comfort, convenience, and elegance expected of an international five-star retreat. From the moment you arrive, our team anticipates your needs with discreet, personalised service that defines true luxury hospitality.\n\nOur facilities span wellness, dining, business, and leisure — each designed to complement your exploration of Kathmandu while providing a sanctuary of calm when you return.",
    caption:
      "Inspired by Nepalese hospitality, surrounded by comfort to offer a truly different experience.",
    ctaText: "Explore Our Facilities",
    ctaHref: routes.about,
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    media: {
      type: "image",
      imageSrc: "/media/dining/skyz-lounge.jpg",
      videoSrc: "",
      poster: "",
      alt: "Premium hotel lounge and amenities",
      caption: "Premium Amenities",
    },
  },
  fineDiningSection: {
    eyebrow: "Fine Dining",
    title: "Garden View & Korean Restaurant",
    description:
      "Garden View & Korean Restaurant offers a relaxing dining experience with beautiful ambiance, delicious cuisine, and memorable hospitality.",
    ctaText: "Explore Dining",
    ctaHref: routes.dining,
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    media: {
      type: "image",
      imageSrc: "/media/dining/korean-restaurant.jpg",
      videoSrc: "",
      poster: "",
      alt: "Garden View and Korean Restaurant terrace",
      caption: "Fine Dining",
    },
  },
  lobbyCafeSection: {
    enabled: true,
    eyebrow: "Lobby Café",
    title: "Cafe in Lobby Area",
    description:
      "Enjoy premium coffee and relaxing moments at our lobby café, perfect for meetings and casual conversations.",
    ctaText: "View Café Experience",
    ctaHref: routes.dining,
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    media: {
      type: "image",
      imageSrc: "/media/dining/lobby-cafe.jpg",
      videoSrc: "",
      poster: "",
      alt: "Premium coffee at the lobby café",
      caption: "Lobby Café",
    },
  },
  rooftopExperienceSection: {
    enabled: true,
    eyebrow: "Rooftop Experience",
    title: "Sky Lounge Restaurant & Bar",
    description:
      "Experience rooftop dining, refreshing drinks, and a beautiful atmosphere at Sky Lounge Restaurant & Bar.",
    ctaText: "Explore Sky Lounge",
    ctaHref: routes.dining,
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    media: {
      type: "image",
      imageSrc: "/media/dining/skyz-lounge.jpg",
      videoSrc: "",
      poster: "",
      alt: "Sky Lounge Restaurant & Bar rooftop dining",
      caption: "Rooftop Experience",
    },
  },
  spaWellnessSection: {
    enabled: true,
    eyebrow: "SPA & WELLNESS",
    title: "SPA & WELLNESS",
    description: "Relax and refresh with our premium spa and wellness experiences designed for complete comfort.",
    treatments: [
      {
        id: "t1",
        enabled: true,
        order: 0,
        title: "Ayurvedic Massage",
        description: "Traditional herbal oil massage with a restorative calm.",
        icon: "leaf",
      },
      {
        id: "t2",
        enabled: true,
        order: 1,
        title: "Hot Stone Ritual",
        description: "Warm river stones therapy to melt away tension.",
        icon: "flame",
      },
      {
        id: "t3",
        enabled: true,
        order: 2,
        title: "Nepali Flower Bath",
        description: "Relaxing floral bath with essential oils and mineral salts.",
        icon: "flower",
      },
      {
        id: "t4",
        enabled: true,
        order: 3,
        title: "Head & Scalp Therapy",
        description: "Tibetan pressure point massage with soothing care.",
        icon: "brain",
      },
      {
        id: "t5",
        enabled: true,
        order: 4,
        title: "Steam & Detox",
        description: "Deep cleanse and detoxify for body and mind.",
        icon: "waves",
      },
      {
        id: "t6",
        enabled: true,
        order: 5,
        title: "Herbal Body Scrub",
        description: "Exfoliating scrub with Himalayan herbs and minerals.",
        icon: "droplets",
      },
      {
        id: "t7",
        enabled: true,
        order: 6,
        title: "Yoga & Meditation",
        description: "Balanced breathing sessions to restore inner harmony.",
        icon: "waves",
      },
      {
        id: "t8",
        enabled: true,
        order: 7,
        title: "Reflexology",
        description: "Foot therapy to restore balance and relaxation.",
        icon: "footprints",
      },
      {
        id: "t9",
        enabled: true,
        order: 8,
        title: "Couple Spa",
        description: "Relax together with our couple wellness rituals.",
        icon: "couple",
      },
      {
        id: "t10",
        enabled: true,
        order: 9,
        title: "Detox Wrap",
        description: "Himalayan clay wrap to refresh and rejuvenate.",
        icon: "droplets",
      },
      {
        id: "t11",
        enabled: true,
        order: 10,
        title: "Aromatherapy",
        description: "Essential oil therapy to relax, heal and uplift your senses.",
        icon: "leaf",
      },
    ],
    ctaText: "EXPLORE WELLNESS",
    ctaHref: "https://hotelthamelparkspa.com/",
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    cardsGapPx: 16,
    cardPaddingPx: 16,
    cardRadiusPx: 18,
    cardHoverLiftPx: 2,
    imageTopOffsetPx: 8,
    treatmentRoomsCard: {
      enabled: true,
      number: "11",
      label: "Treatment Rooms",
      backgroundColor: "#FBF8F1",
      textColor: "#062C24",
      borderColor: "#C5A05955",
      shadow: "0 22px 48px rgba(15, 42, 34, 0.14)",
      accentColor: "#0B3A31",
      widthPx: 250,
      heightPx: 108,
      leftPx: -18,
      bottomPx: 20,
    },
    media: {
      type: "image",
      imageSrc: "/media/spa/wellness.jpg",
      videoSrc: "",
      poster: "",
      alt: "Spa & Wellness treatment",
      caption: "Spa & Wellness",
    },
  },
  meetingsEventsSection: {
    enabled: true,
    eyebrow: "EVENTS & MEETINGS",
    title: "Meetings & Events",
    description:
      "World-class event facilities with Himalayan backdrops — from intimate business gatherings to grand celebrations.",
    statsEyebrow: "EVENT CAPACITIES",
    stats: [
      { id: "s1", value: "5", label: "Event Spaces", enabled: true, order: 0 },
      { id: "s2", value: "400", label: "Max Guests", enabled: true, order: 1 },
      { id: "s3", value: "750m²", label: "Event Area", enabled: true, order: 2 },
    ],
    checklist: [
      { id: "c1", text: "State-of-the-art AV & Conference Technology", enabled: true, order: 0 },
      { id: "c2", text: "Himalayan View Boardroom", enabled: true, order: 1 },
      { id: "c3", text: "Grand Ballroom for Weddings", enabled: true, order: 2 },
      { id: "c4", text: "Dedicated Event Planning Team", enabled: true, order: 3 },
      { id: "c5", text: "High-Speed Internet", enabled: true, order: 4 },
      { id: "c6", text: "Outdoor Rooftop Event Space", enabled: true, order: 5 },
    ],
    cardBackgroundColor: "#FBF8F1",
    cardBorderColor: "#C5A05955",
    ctaText: "REQUEST A PROPOSAL",
    ctaHref: routes.meetingsEvents,
    ctaVisible: true,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    sectionPaddingY: 96,
    featuredTitle: "Grand Ballroom",
    featuredDescription: "Timeless celebrations in grandeur",
    media: {
      type: "image",
      imageSrc: "/media/events/ballroom.jpg",
      videoSrc: "",
      poster: "",
      alt: "Luxury ballroom at Hotel Thamel Park",
      caption: "Grand Ballroom",
    },
    featureCards: [
      {
        id: "fc-business",
        enabled: true,
        order: 0,
        title: "BUSINESS MEETINGS",
        description: "Professional spaces for productive meetings.",
        icon: "users",
        media: {
          type: "image",
          imageSrc: "/media/events/conference.jpg",
          videoSrc: "",
          poster: "",
          alt: "Business meeting boardroom",
          caption: "Business Meetings",
        },
      },
      {
        id: "fc-wedding",
        enabled: true,
        order: 1,
        title: "WEDDINGS & CELEBRATIONS",
        description: "Magical venues for your special moments.",
        icon: "rings",
        media: {
          type: "image",
          imageSrc: "/media/events/wedding.jpg",
          videoSrc: "",
          poster: "",
          alt: "Wedding celebration venue",
          caption: "Weddings & Celebrations",
        },
      },
      {
        id: "fc-social",
        enabled: true,
        order: 2,
        title: "SOCIAL EVENTS",
        description: "Unforgettable gatherings in stunning settings.",
        icon: "cloche",
        media: {
          type: "image",
          imageSrc: "/media/dining/skyz-lounge.jpg",
          videoSrc: "",
          poster: "",
          alt: "Rooftop social event",
          caption: "Social Events",
        },
      },
    ],
  },
  exploreKathmanduSection: {
    enabled: true,
    eyebrow: "EXPLORE KATHMANDU",
    titlePrimary: "Sightseeing",
    titleAccent: "& Day Trips",
    description:
      "Our cultural concierge team arranges private and group excursions to Kathmandu Valley's most iconic UNESCO World Heritage sites and hidden gems.",
    destinations: [
      {
        id: "dest-swayambhu",
        enabled: true,
        order: 0,
        category: "HERITAGE SITE • UNESCO",
        title: "Swayambhunath Stupa",
        description:
          "The iconic Monkey Temple overlooking Kathmandu — ancient stupas, prayer flags, and panoramic valley views.",
        distance: "1.5 km",
        href: "/cultural-experience",
        icon: "stupa",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/culture/nepali-culture.jpg",
          videoSrc: "",
          poster: "",
          alt: "Swayambhunath Stupa at sunset",
          caption: "Swayambhunath",
        },
      },
      {
        id: "dest-durbar",
        enabled: true,
        order: 1,
        category: "HISTORIC • UNESCO",
        title: "Kathmandu Durbar Square",
        description:
          "Palaces, courtyards, and living heritage in the historic heart of the old city.",
        distance: "3 km",
        href: "/cultural-experience",
        icon: "pagoda",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/01.jpg",
          videoSrc: "",
          poster: "",
          alt: "Kathmandu Durbar Square",
          caption: "Durbar Square",
        },
      },
      {
        id: "dest-boudha",
        enabled: true,
        order: 2,
        category: "BUDDHIST • UNESCO",
        title: "Boudhanath Stupa",
        description:
          "One of the world's largest stupas — serene circumambulation, butter lamps, and Himalayan spirituality.",
        distance: "4 km",
        href: "/cultural-experience",
        icon: "stupa",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/02.jpg",
          videoSrc: "",
          poster: "",
          alt: "Boudhanath Stupa",
          caption: "Boudhanath",
        },
      },
      {
        id: "dest-pashupati",
        enabled: true,
        order: 3,
        category: "HINDU TEMPLE • UNESCO",
        title: "Pashupatinath Temple",
        description:
          "Sacred Hindu sanctuary on the Bagmati — rituals, architecture, and profound cultural immersion.",
        distance: "5 km",
        href: "/cultural-experience",
        icon: "trident",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/03.jpg",
          videoSrc: "",
          poster: "",
          alt: "Pashupatinath Temple",
          caption: "Pashupatinath",
        },
      },
      {
        id: "dest-nagarkot",
        enabled: true,
        order: 4,
        category: "NATURE • SUNRISE VIEW",
        title: "Nagarkot Hill Station",
        description:
          "Himalayan sunrise vistas and crisp mountain air — an unforgettable day escape from the city.",
        distance: "35 km • Day Trip",
        href: "/cultural-experience",
        icon: "mountain",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/04.jpg",
          videoSrc: "",
          poster: "",
          alt: "Nagarkot Himalayan sunrise",
          caption: "Nagarkot",
        },
      },
      {
        id: "dest-garden",
        enabled: true,
        order: 5,
        category: "GARDEN • HERITAGE",
        title: "Garden of Dreams",
        description:
          "An Edwardian neo-classical garden oasis — fountains, pavilions, and quiet luxury near Thamel.",
        distance: "0.8 km",
        href: "/cultural-experience",
        icon: "lotus",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/05.jpg",
          videoSrc: "",
          poster: "",
          alt: "Garden of Dreams pavilion",
          caption: "Garden of Dreams",
        },
      },
      {
        id: "dest-palace",
        enabled: true,
        order: 6,
        category: "MUSEUM • CULTURE",
        title: "Narayanhiti Palace Museum",
        description:
          "Former royal residence turned museum — history, grandeur, and Nepal's modern monarchy era.",
        distance: "2 km",
        href: "/cultural-experience",
        icon: "palace",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/06.jpg",
          videoSrc: "",
          poster: "",
          alt: "Narayanhiti Palace Museum",
          caption: "Narayanhiti",
        },
      },
      {
        id: "dest-chandragiri",
        enabled: true,
        order: 7,
        category: "ADVENTURE • CULTURE",
        title: "Chandragiri Hills",
        description:
          "Cable-car ascent to mountain temples and sweeping valley panoramas — adventure with elegance.",
        distance: "22 km • Half Day",
        href: "/cultural-experience",
        icon: "cablecar",
        iconSrc: "",
        media: {
          type: "image",
          imageSrc: "/media/gallery/01.jpg",
          videoSrc: "",
          poster: "",
          alt: "Chandragiri Hills viewpoint",
          caption: "Chandragiri",
        },
      },
    ],
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    cardBackgroundColor: "#FBF8F1",
    cardBorderColor: "#C5A05966",
    sectionPaddingY: 96,
    cardsGapPx: 22,
  },
  culturalExperiencePage: {
    hero: {
      title: "Cultural Experience",
      subtitle: "Nepali Heritage",
      description:
        "Immerse yourself in the traditions, temples, cuisine, and living heritage of Kathmandu Valley.",
      imageSrc: "/media/culture/nepali-culture.jpg",
      media: {
        type: "image",
        imageSrc: "/media/culture/nepali-culture.jpg",
        videoSrc: "",
        poster: "",
        alt: "Cultural experience in Kathmandu",
        caption: "",
      },
    },
    seo: {
      title: "Cultural Experience | Hotel Thamel Park",
      description:
        "Discover authentic Nepali culture, UNESCO heritage, local cuisine, temples, and curated Kathmandu experiences at Hotel Thamel Park.",
      canonical: "/cultural-experience",
      ogImage: "/media/culture/nepali-culture.jpg",
    },
    story: {
      title: "The Soul of Kathmandu",
      content: CULTURE_PAGE_STORY,
    },
    gallery: [
      { id: "cg1", src: "/media/culture/nepali-culture.jpg", title: "Heritage Courtyard", alt: "Traditional Nepali courtyard" },
      { id: "cg2", src: "/media/gallery/01.jpg", title: "Temple Architecture", alt: "Pagoda temple architecture" },
      { id: "cg3", src: "/media/gallery/02.jpg", title: "Local Festival", alt: "Nepali festival celebration" },
      { id: "cg4", src: "/media/gallery/03.jpg", title: "Artisan Craft", alt: "Traditional artisan workshop" },
      { id: "cg5", src: "/media/gallery/04.jpg", title: "Himalayan Vista", alt: "Himalayan mountain view from Kathmandu" },
      { id: "cg6", src: "/media/gallery/05.jpg", title: "Cultural Dining", alt: "Traditional Nepali dining" },
    ],
    timeline: [
      { year: "Day 1", title: "Arrival & Orientation", description: "Welcome ritual, Thamel heritage walk, and sunset viewpoints." },
      { year: "Day 2", title: "UNESCO Heritage Circuit", description: "Swayambhunath, Boudhanath, and Pashupatinath with expert guide." },
      { year: "Day 3", title: "Art & Architecture", description: "Patan and Bhaktapur Durbar Squares, artisan workshops, and local lunch." },
      { year: "Day 4", title: "Culinary Journey", description: "Market visit, cooking class, and Newari feast experience." },
      { year: "Day 5", title: "Mountain Excursion", description: "Nagarkot sunrise or Chandragiri cable car with panoramic views." },
    ],
    experienceCards: [
      { id: "e1", title: "Private Heritage Tours", description: "Expert-led walks through UNESCO sites and hidden courtyards.", icon: "Landmark" },
      { id: "e2", title: "Temple Ceremonies", description: "Morning prayers and evening aarti at sacred sites.", icon: "Church" },
      { id: "e3", title: "Local Food Trails", description: "Curated tastings from street food to fine Newari dining.", icon: "UtensilsCrossed" },
      { id: "e4", title: "Festival Experiences", description: "Seasonal celebrations with cultural context and access.", icon: "Sparkles" },
      { id: "e5", title: "Artisan Workshops", description: "Brass, thangka, pottery, and woodcarving demonstrations.", icon: "Palette" },
      { id: "e6", title: "Luxury Concierge", description: "Personalised itineraries blending culture with five-star comfort.", icon: "ConciergeBell" },
    ],
    faq: [
      {
        id: "f1",
        question: "How far are UNESCO sites from the hotel?",
        answer: "Most major heritage sites are within 20–45 minutes by car. Our concierge arranges private transport and expert guides.",
      },
      {
        id: "f2",
        question: "Can you arrange authentic local dining?",
        answer: "Yes. We offer curated restaurant reservations, private Newari feasts, cooking classes, and guided food walks in Thamel and beyond.",
      },
      {
        id: "f3",
        question: "Are cultural tours suitable for families?",
        answer: "Absolutely. We tailor walking tours, temple visits, and festival experiences for all ages and mobility levels.",
      },
      {
        id: "f4",
        question: "When is the best time to visit for festivals?",
        answer: "Dashain (September–October) and Tihar (October–November) are peak festival seasons. Holi (March) and Indra Jatra (September) are also spectacular.",
      },
    ],
  },
  facilities: [
    { id: "wifi", name: "Free Wi-Fi", description: "High-speed internet throughout the hotel.", icon: "Wifi", enabled: true, order: 0 },
    { id: "transfer", name: "Airport Transfer", description: "Seamless arrival and departure assistance.", icon: "Plane", enabled: true, order: 1 },
    { id: "room-service", name: "Room Service", description: "In-room dining available around the clock.", icon: "ConciergeBell", enabled: true, order: 2 },
    { id: "restaurant", name: "Restaurant", description: "Fine dining with international and local cuisine.", icon: "UtensilsCrossed", enabled: true, order: 3 },
    { id: "lounge", name: "Lounge", description: "Elegant rooftop lounge with panoramic views.", icon: "Wine", enabled: true, order: 4 },
    { id: "spa", name: "Spa", description: "Premium wellness treatments and therapies.", icon: "Flower2", enabled: true, order: 5 },
    { id: "family", name: "Family Rooms", description: "Spacious accommodations for families.", icon: "Users", enabled: true, order: 6 },
    { id: "housekeeping", name: "Daily Housekeeping", description: "Impeccable room maintenance every day.", icon: "Sparkle", enabled: true, order: 7 },
    { id: "front-desk", name: "Front Desk 24/7", description: "Always available for your needs.", icon: "Clock", enabled: true, order: 8 },
    { id: "sauna", name: "Sauna & Steam", description: "Rejuvenating thermal wellness experiences.", icon: "Flame", enabled: true, order: 9 },
  ],
  rooms: [
    {
      id: "super-deluxe-twin",
      name: "Super Deluxe Twin Room",
      price: 60,
      guests: "2 Guests",
      size: "32 m²",
      bedType: "Twin Beds",
      features: ["Twin Beds", "City View", "En-suite Bathroom", "Climate Control"],
      description:
        "An exquisite twin room offering refined comfort with elegant furnishings and serene ambiance for discerning travelers.",
      longDescription:
        "The Super Deluxe Twin Room is designed for travellers who appreciate space, symmetry, and refined detail. Twin beds dressed in premium linens, a dedicated work area, and a serene city outlook create an atmosphere of calm sophistication. En-suite marble bathroom, climate control, and complimentary high-speed Wi-Fi complete your sanctuary in Thamel.",
      imageSrc: "/media/rooms/super-deluxe-twin.jpg",
      gallery: ["/media/rooms/super-deluxe-twin.jpg", "/media/gallery/06.jpg", "/media/gallery/01.jpg"],
      amenities: ["Twin Beds", "City View", "En-suite Bathroom", "Climate Control", "Premium Linens", "Complimentary Wi-Fi"],
      policies: DEFAULT_ROOM_POLICIES,
    },
    {
      id: "super-deluxe",
      name: "Super Deluxe Room",
      price: 60,
      guests: "2 Guests",
      size: "35 m²",
      bedType: "King Bed",
      features: ["King Bed", "Garden View", "Mini Bar", "Premium Linens"],
      description:
        "A spacious sanctuary of luxury featuring a king bed, sophisticated décor, and every amenity for an exceptional stay.",
      longDescription:
        "Our Super Deluxe Room is a generous retreat featuring a king bed, garden-facing views, and interiors composed in warm cream and sage tones. A curated mini bar, seating area, and premium bath amenities elevate every moment. Ideal for couples and solo travellers seeking understated luxury in the heart of Kathmandu.",
      imageSrc: "/media/rooms/super-deluxe.jpg",
      gallery: ["/media/rooms/super-deluxe.jpg", "/media/gallery/02.jpg", "/media/gallery/03.jpg"],
      amenities: ["King Bed", "Garden View", "Mini Bar", "Premium Linens", "Seating Area", "In-room Safe"],
      policies: DEFAULT_ROOM_POLICIES,
    },
    {
      id: "family-room",
      name: "Family Room",
      price: 55,
      guests: "3–4 Guests",
      size: "42 m²",
      bedType: "Multiple Beds",
      features: ["Family Friendly", "Spacious", "Seating Area", "Extra Storage"],
      description:
        "Generously designed for families, combining comfort and space with thoughtful amenities for memorable stays.",
      longDescription:
        "The Family Room offers generous proportions for parents and children travelling together. Multiple sleeping configurations, a spacious seating area, and additional storage ensure everyone enjoys comfort and privacy. Thoughtful touches — from extra towels to flexible bedding — reflect our commitment to family hospitality at a luxury standard.",
      imageSrc: "/media/rooms/family-room.jpg",
      gallery: ["/media/rooms/family-room.jpg", "/media/gallery/04.jpg", "/media/gallery/05.jpg"],
      amenities: ["Family Friendly", "Spacious Layout", "Seating Area", "Extra Storage", "Climate Control", "Complimentary Wi-Fi"],
      policies: DEFAULT_ROOM_POLICIES,
    },
    {
      id: "standard-deluxe",
      name: "Standard Deluxe Room",
      price: 50,
      guests: "2 Guests",
      size: "28 m²",
      bedType: "Queen Bed",
      features: ["Queen Bed", "Premium Comfort", "Work Space", "Complimentary WiFi"],
      description:
        "Elegant simplicity meets luxury comfort in our thoughtfully curated standard deluxe accommodation.",
      longDescription:
        "The Standard Deluxe Room distils our luxury philosophy into an elegantly efficient space. A queen bed with premium linens, dedicated work surface, and refined bath amenities provide everything discerning travellers require. Perfect for business visits and cultural explorers who value quality without excess.",
      imageSrc: "/media/rooms/standard-deluxe.jpg",
      gallery: ["/media/rooms/standard-deluxe.jpg", "/media/gallery/06.jpg", "/media/gallery/02.jpg"],
      amenities: ["Queen Bed", "Premium Comfort", "Work Space", "Complimentary WiFi", "En-suite Bathroom", "Daily Housekeeping"],
      policies: DEFAULT_ROOM_POLICIES,
    },
  ],
  roomBooking: {
    submitLabel: "Confirm Reservation",
    payOnlineLabel: "Pay Online",
    payAtHotelLabel: "Pay At Hotel",
    specialRequestLabel: "Special Requests",
    availabilityNote: "Complete your details below. Our team will confirm your reservation promptly.",
    breakfastRoomOnlyLabel: "Room Only",
    breakfastWithLabel: "With Breakfast",
    breakfastNote: "Breakfast is served daily at our Garden Restaurant from 7:00 AM to 10:30 AM.",
    confirmationTitle: "Reservation Received",
    confirmationMessage: "Thank you. Your booking request has been received. We will confirm availability and send details to your email shortly.",
  },
  diningPage: {
    hero: {
      title: "Culinary Excellence",
      subtitle: "Dining",
      description: "From authentic Korean cuisine to rooftop evenings, every meal is an occasion.",
      imageSrc: "/media/dining/korean-restaurant.jpg",
    },
    seo: {
      title: "Dining | Hotel Thamel Park",
      description: "Fine dining, Korean restaurant, and Sky Lounge at Hotel Thamel Park, Kathmandu.",
    },
    intro: {
      title: "A World of Flavors",
      content:
        "Our restaurants celebrate global cuisine with local soul — crafted by expert chefs in settings designed for memorable dining experiences.",
    },
    venues: [
      {
        id: "korean-restaurant",
        name: "Garden View Korean Restaurant",
        tagline: "Authentic flavors in an elegant garden sanctuary",
        description:
          "Savor authentic Korean cuisine in a serene garden setting, where premium ingredients and warm hospitality create unforgettable meals.",
        features: ["Authentic Korean Cuisine", "Premium Ingredients", "Garden Ambience", "Family Dining"],
        imageSrc: "/media/dining/korean-restaurant.jpg",
      },
      {
        id: "sky-lounge",
        name: "Sky Lounge Restaurant & Bar",
        tagline: "Elevated evenings above the Kathmandu skyline",
        description:
          "Experience rooftop dining with signature cocktails, panoramic city views, and an atmosphere of refined celebration.",
        features: ["Rooftop Views", "Signature Cocktails", "Live Atmosphere", "Private Events"],
        imageSrc: "/media/dining/skyz-lounge.jpg",
      },
      {
        id: "lobby-cafe",
        name: "Lobby Cafe",
        tagline: "Premium coffee and quiet moments",
        description:
          "Begin your day with artisan coffee or unwind with light fare in our elegant lobby cafe — perfect for meetings and relaxation.",
        features: ["Artisan Coffee", "Light Fare", "All-Day Service", "Meeting Friendly"],
        imageSrc: "/media/dining/lobby-cafe.jpg",
      },
    ],
    highlights: [
      { title: "Chef-Crafted Menus", description: "Seasonal ingredients prepared with international expertise." },
      { title: "Private Dining", description: "Intimate settings for celebrations and business gatherings." },
      { title: "Wine Selection", description: "Curated wines paired with every course." },
    ],
    gallery: [
      { id: "d1", src: "/media/dining/korean-restaurant.jpg", title: "Garden Restaurant" },
      { id: "d2", src: "/media/dining/skyz-lounge.jpg", title: "Sky Lounge" },
      { id: "d3", src: "/media/dining/lobby-cafe.jpg", title: "Lobby Cafe" },
    ],
    cta: {
      title: "Reserve Your Table",
      description: "Our concierge team is ready to arrange your perfect dining experience.",
      buttonText: "Make a Reservation",
    },
  },
  spaPage: {
    hero: {
      title: "Spa & Wellness",
      subtitle: "Rejuvenation",
      description: "A sanctuary dedicated to restoration, renewal, and the art of well-being.",
      imageSrc: "/media/spa/wellness.jpg",
    },
    seo: {
      title: "Spa & Wellness | Hotel Thamel Park",
      description: "Luxury spa treatments, massage, sauna, and wellness at Hotel Thamel Park.",
    },
    philosophy: {
      title: "The Art of Renewal",
      content:
        "Our wellness sanctuary blends time-honored healing traditions with contemporary luxury. Each treatment is a bespoke journey designed to restore harmony to body, mind, and spirit.",
      imageSrc: "/media/spa/treatment.jpg",
    },
    services: [
      { id: "massage", name: "Massage", description: "Therapeutic and relaxation massage treatments tailored to your needs." },
      { id: "steam", name: "Steam", description: "Purifying steam sessions to detoxify and rejuvenate the body." },
      { id: "sauna", name: "Sauna", description: "Traditional sauna experiences for deep relaxation and wellness." },
      { id: "waxing", name: "Waxing", description: "Professional grooming services in a serene spa environment." },
      { id: "wellness", name: "Wellness Packages", description: "Comprehensive spa journeys combining multiple treatments." },
      { id: "aromatherapy", name: "Aromatherapy", description: "Essential oil blends to harmonize body, mind, and spirit." },
    ],
    gallery: [
      { id: "s1", src: "/media/spa/wellness.jpg", title: "Wellness Haven" },
      { id: "s2", src: "/media/spa/treatment.jpg", title: "Spa Treatment" },
      { id: "s3", src: "/media/gallery/05.jpg", title: "Thermal Suite" },
    ],
    cta: {
      title: "Book Your Appointment",
      description: "Reserve your wellness journey with our spa concierge team.",
      buttonText: "Schedule Treatment",
    },
  },
  meetingsEventsPage: {
    hero: {
      title: "Meetings & Events",
      subtitle: "Celebrations & Conferences",
      description:
        "Extraordinary venues for corporate gatherings, weddings, and milestone celebrations — framed by Himalayan elegance.",
      imageSrc: "/media/pages/meetings.jpg",
      ctaText: "Request a Proposal",
      ctaHref: "#event-inquiry",
      media: {
        type: "image",
        imageSrc: "/media/pages/meetings.jpg",
        videoSrc: "",
        poster: "",
        alt: "Meetings and events at Hotel Thamel Park",
        caption: "",
      },
    },
    seo: {
      title: "Meetings & Events | Hotel Thamel Park",
      description:
        "Host luxury conferences, weddings, and corporate events at Hotel Thamel Park. Grand ballroom, boardrooms, rooftop venues, and dedicated event planning in Kathmandu.",
      canonical: "/meetings-events",
      ogImage: "/media/pages/meetings.jpg",
      keywords:
        "meetings events kathmandu, wedding venue nepal, conference hall thamel, corporate events hotel, ballroom kathmandu",
    },
    about: {
      eyebrow: "About Our Venues",
      title: "World-Class Event Spaces",
      content:
        "From intimate boardroom sessions to grand ballroom celebrations, Hotel Thamel Park offers versatile venues designed with five-star precision. Our dedicated events team crafts bespoke experiences — seamless AV, refined catering, and Himalayan-inspired ambiance for every occasion.",
      media: {
        type: "image",
        imageSrc: "/media/events/ballroom.jpg",
        videoSrc: "",
        poster: "",
        alt: "Grand event space overview",
        caption: "Event Spaces",
      },
    },
    spaces: [
      {
        id: "conference",
        enabled: true,
        order: 0,
        title: "Conference Hall",
        subtitle: "Corporate Excellence",
        description:
          "Our flagship conference hall accommodates large assemblies with theatre, classroom, or banquet configurations. Floor-to-ceiling windows frame Kathmandu views while state-of-the-art AV ensures flawless presentations.",
        capacity: "Up to 250 guests",
        features: ["Theatre & classroom layouts", "4K projection & sound", "Breakout foyer", "Dedicated technician"],
        media: {
          type: "image",
          imageSrc: "/media/events/conference.jpg",
          videoSrc: "",
          poster: "",
          alt: "Conference hall",
          caption: "",
        },
      },
      {
        id: "wedding",
        enabled: true,
        order: 1,
        title: "Wedding Hall",
        subtitle: "Unforgettable Celebrations",
        description:
          "Create the wedding of your dreams in our grand ballroom — crystal chandeliers, bespoke floral design, and a bridal suite for preparations. Our team orchestrates every detail with grace and precision.",
        capacity: "Up to 400 guests",
        features: ["Custom décor packages", "Bridal suite access", "Live music staging", "Premium catering menus"],
        media: {
          type: "image",
          imageSrc: "/media/events/wedding.jpg",
          videoSrc: "",
          poster: "",
          alt: "Wedding hall",
          caption: "",
        },
      },
      {
        id: "boardroom",
        enabled: true,
        order: 2,
        title: "Business Meeting Room",
        subtitle: "Executive Precision",
        description:
          "A refined boardroom with Himalayan views — ideal for executive meetings, investor presentations, and confidential discussions. Premium refreshments and high-speed connectivity included.",
        capacity: "Up to 20 guests",
        features: ["Video conferencing", "Smart display", "Executive seating", "Privacy assured"],
        media: {
          type: "image",
          imageSrc: "/media/events/conference.jpg",
          videoSrc: "",
          poster: "",
          alt: "Executive boardroom",
          caption: "",
        },
      },
      {
        id: "rooftop",
        enabled: true,
        order: 3,
        title: "Rooftop Events",
        subtitle: "Skyline Celebrations",
        description:
          "Elevate your gathering on our rooftop terrace — sunset cocktails, live entertainment, and panoramic mountain views create an unforgettable open-air experience.",
        capacity: "Up to 120 guests",
        features: ["Open-air terrace", "Mountain panoramas", "Bar service", "Evening lighting design"],
        media: {
          type: "image",
          imageSrc: "/media/dining/skyz-lounge.jpg",
          videoSrc: "",
          poster: "",
          alt: "Rooftop event space",
          caption: "",
        },
      },
    ],
    facilities: [
      { id: "f1", enabled: true, order: 0, title: "Audio Visual", description: "Professional sound and vision systems", icon: "Mic" },
      { id: "f2", enabled: true, order: 1, title: "Projector", description: "4K projection and large-format screens", icon: "Projector" },
      { id: "f3", enabled: true, order: 2, title: "WiFi", description: "High-speed fibre throughout all venues", icon: "Wifi" },
      { id: "f4", enabled: true, order: 3, title: "Stage", description: "Modular staging for performances", icon: "Presentation" },
      { id: "f5", enabled: true, order: 4, title: "Lighting", description: "Programmable ambient and spot lighting", icon: "Lightbulb" },
      { id: "f6", enabled: true, order: 5, title: "Parking", description: "Secure guest and delegate parking", icon: "Car" },
      { id: "f7", enabled: true, order: 6, title: "Catering", description: "Banquet and cocktail menu options", icon: "UtensilsCrossed" },
      { id: "f8", enabled: true, order: 7, title: "Decoration", description: "Floral and thematic event styling", icon: "Flower2" },
      { id: "f9", enabled: true, order: 8, title: "Air Conditioning", description: "Climate-controlled comfort year-round", icon: "Wind" },
      { id: "f10", enabled: true, order: 9, title: "Photography", description: "Preferred photographer partnerships", icon: "Camera" },
    ],
    gallery: [
      { id: "g1", enabled: true, order: 0, src: "/media/events/ballroom.jpg", title: "Grand Ballroom", alt: "Grand ballroom setup" },
      { id: "g2", enabled: true, order: 1, src: "/media/events/wedding.jpg", title: "Wedding Reception", alt: "Wedding reception" },
      { id: "g3", enabled: true, order: 2, src: "/media/events/conference.jpg", title: "Conference Setup", alt: "Conference seating" },
      { id: "g4", enabled: true, order: 3, src: "/media/dining/skyz-lounge.jpg", title: "Rooftop Evening", alt: "Rooftop event" },
      { id: "g5", enabled: true, order: 4, src: "/media/gallery/01.jpg", title: "Elegant Details", alt: "Event table setting" },
    ],
    whyChooseUs: [
      {
        id: "w1",
        enabled: true,
        order: 0,
        title: "Dedicated Event Team",
        description: "Personal coordinators from proposal to farewell — every detail managed with five-star care.",
      },
      {
        id: "w2",
        enabled: true,
        order: 1,
        title: "Himalayan Ambience",
        description: "Venues infused with Nepalese heritage and mountain views — distinctive and memorable.",
      },
      {
        id: "w3",
        enabled: true,
        order: 2,
        title: "Culinary Excellence",
        description: "Award-winning kitchens deliver bespoke menus for every occasion and dietary requirement.",
      },
      {
        id: "w4",
        enabled: true,
        order: 3,
        title: "Prime Thamel Location",
        description: "Central Kathmandu access for international delegates and wedding guests alike.",
      },
    ],
    faq: [
      {
        id: "q1",
        enabled: true,
        order: 0,
        question: "How far in advance should we book?",
        answer: "We recommend booking 3–6 months ahead for weddings and large conferences. Smaller meetings can often be arranged within 2–4 weeks, subject to availability.",
      },
      {
        id: "q2",
        enabled: true,
        order: 1,
        question: "Do you provide in-house catering?",
        answer: "Yes. Our culinary team offers full banquet, cocktail, and coffee-break menus. Custom tasting sessions are available for wedding and gala clients.",
      },
      {
        id: "q3",
        enabled: true,
        order: 2,
        question: "Can you arrange accommodation for guests?",
        answer: "Absolutely. We offer preferential room blocks and suite packages for event delegates and wedding parties staying at the hotel.",
      },
      {
        id: "q4",
        enabled: true,
        order: 3,
        question: "Is AV equipment included?",
        answer: "Standard AV is included with venue hire. Advanced production, live streaming, and dedicated technicians can be arranged on request.",
      },
    ],
    form: {
      title: "Request a Proposal",
      description: "Share your event vision and our team will respond within one business day.",
      submitLabel: "Submit Inquiry",
      successTitle: "Thank You",
      successMessage:
        "Your event inquiry has been received. Our events team will contact you shortly with a tailored proposal.",
      eventTypes: ["Wedding", "Conference", "Meeting", "Birthday", "Corporate", "Other"],
    },
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
  },
  aboutPage: {
    hero: {
      title: "ABOUT HOTEL THAMEL PARK & SPA",
      subtitle: "Luxury Hospitality in the Heart of Kathmandu",
      description:
        "Experience timeless elegance, authentic Nepali hospitality, exceptional comfort and unforgettable moments.",
      imageSrc:
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=2000&q=80",
      breadcrumbHome: "Home",
      breadcrumbCurrent: "About Us",
      overlayOpacity: 0.45,
    },
    story: {
      eyebrow: "Our Heritage",
      title: "Our Story",
      content:
        "Nestled in the vibrant heart of Thamel, Hotel Thamel Park & Spa has grown into a sanctuary of refined comfort and authentic Nepalese warmth. From our thoughtfully designed rooms to our wellness rituals and culinary journeys, every detail is crafted to welcome discerning travelers with grace. We believe luxury is not only what you see — it is how you feel: cared for, restored, and inspired by Kathmandu’s timeless spirit.",
      imageSrc:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      signature: "The Thamel Park Family",
      signatureRole: "Hospitality with Heart",
    },
    stats: [
      { id: "s1", enabled: true, order: 1, value: "20+", label: "Years of Hospitality" },
      { id: "s2", enabled: true, order: 2, value: "84", label: "Luxury Rooms" },
      { id: "s3", enabled: true, order: 3, value: "25K+", label: "Happy Guests" },
      { id: "s4", enabled: true, order: 4, value: "4.9★", label: "Guest Satisfaction" },
    ],
    philosophy: {
      eyebrow: "What Guides Us",
      title: "Our Philosophy",
      content:
        "We blend international luxury standards with the soul of Nepali hospitality — creating spaces where elegance meets genuine warmth.",
      mission: {
        title: "Mission",
        content:
          "To deliver exceptional luxury hospitality that honors Nepalese warmth while exceeding the expectations of discerning global travelers.",
        icon: "compass",
      },
      vision: {
        title: "Vision",
        content:
          "To be recognized as Kathmandu’s premier boutique luxury hotel — where every guest feels welcomed, restored, and inspired.",
        icon: "eye",
      },
      values: [
        {
          id: "v1",
          enabled: true,
          order: 1,
          title: "Authenticity",
          description: "Genuine Nepali warmth in every greeting and gesture.",
          icon: "heart",
        },
        {
          id: "v2",
          enabled: true,
          order: 2,
          title: "Excellence",
          description: "Meticulous standards across rooms, dining, and wellness.",
          icon: "sparkles",
        },
        {
          id: "v3",
          enabled: true,
          order: 3,
          title: "Care",
          description: "Personalized attention that anticipates every need.",
          icon: "hand-heart",
        },
      ],
    },
    whyChoose: {
      eyebrow: "The Difference",
      title: "Why Choose Hotel Thamel Park",
      description: "A curated collection of experiences that define luxury hospitality in Kathmandu.",
      items: [
        {
          id: "w1",
          enabled: true,
          order: 1,
          title: "Luxury Accommodation",
          description: "Thoughtfully designed rooms with refined comfort and modern amenities.",
          icon: "bed",
        },
        {
          id: "w2",
          enabled: true,
          order: 2,
          title: "Authentic Hospitality",
          description: "Warm Nepalese service that makes every guest feel at home.",
          icon: "smile",
        },
        {
          id: "w3",
          enabled: true,
          order: 3,
          title: "Fine Dining",
          description: "Korean cuisine, lobby café, and rooftop Sky Lounge experiences.",
          icon: "utensils",
        },
        {
          id: "w4",
          enabled: true,
          order: 4,
          title: "Spa & Wellness",
          description: "Restorative treatments, sauna, and steam in a serene sanctuary.",
          icon: "sparkles",
        },
        {
          id: "w5",
          enabled: true,
          order: 5,
          title: "Meetings & Events",
          description: "Elegant venues for celebrations, conferences, and private gatherings.",
          icon: "users",
        },
        {
          id: "w6",
          enabled: true,
          order: 6,
          title: "Prime Thamel Location",
          description: "Steps from culture, cuisine, and Kathmandu’s iconic landmarks.",
          icon: "map-pin",
        },
        {
          id: "w7",
          enabled: true,
          order: 7,
          title: "Personalized Service",
          description: "Concierge care tailored to your journey and celebrations.",
          icon: "gem",
        },
        {
          id: "w8",
          enabled: true,
          order: 8,
          title: "Safe & Secure Stay",
          description: "24/7 reception and a secure environment for peace of mind.",
          icon: "shield",
        },
      ],
    },
    discover: {
      eyebrow: "Immersive Luxury",
      title: "Discover Our Experience",
      content:
        "From serene suites to rooftop evenings and spa rituals, every corner of Hotel Thamel Park invites you to slow down and savor Kathmandu in comfort.",
      images: [
        {
          id: "d1",
          src: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=900&q=80",
          alt: "Luxury hotel suite",
        },
        {
          id: "d2",
          src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80",
          alt: "Fine dining experience",
        },
        {
          id: "d3",
          src: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=80",
          alt: "Spa wellness sanctuary",
        },
      ],
    },
    services: {
      eyebrow: "Amenities",
      title: "Our Services",
      items: [
        { id: "sv1", enabled: true, order: 1, title: "Luxury Rooms", description: "Refined rest for every traveler.", icon: "bed" },
        { id: "sv2", enabled: true, order: 2, title: "Restaurant", description: "Garden View & Korean dining.", icon: "utensils" },
        { id: "sv3", enabled: true, order: 3, title: "Cafe", description: "Lobby café for calm conversations.", icon: "coffee" },
        { id: "sv4", enabled: true, order: 4, title: "Sky Lounge", description: "Rooftop evenings above the city.", icon: "wine" },
        { id: "sv5", enabled: true, order: 5, title: "Spa", description: "Wellness rituals and therapies.", icon: "sparkles" },
        { id: "sv6", enabled: true, order: 6, title: "Meetings", description: "Spaces for business and celebration.", icon: "briefcase" },
        { id: "sv7", enabled: true, order: 7, title: "Airport Transfer", description: "Seamless arrival assistance.", icon: "plane" },
        { id: "sv8", enabled: true, order: 8, title: "Travel Assistance", description: "Tours and local concierge help.", icon: "map" },
        { id: "sv9", enabled: true, order: 9, title: "Room Service", description: "In-room dining around the clock.", icon: "bell" },
        { id: "sv10", enabled: true, order: 10, title: "Laundry", description: "Professional garment care.", icon: "shirt" },
        { id: "sv11", enabled: true, order: 11, title: "Free WiFi", description: "High-speed connectivity throughout.", icon: "wifi" },
        { id: "sv12", enabled: true, order: 12, title: "24/7 Reception", description: "Always available for your needs.", icon: "clock" },
      ],
    },
    team: {
      eyebrow: "People Behind the Experience",
      title: "Our Team",
      description: "Dedicated professionals who bring luxury hospitality to life every day.",
      members: [
        {
          id: "t1",
          enabled: true,
          order: 1,
          name: "Rajesh Sharma",
          position: "General Manager",
          bio: "Leading with vision and a passion for world-class Nepali hospitality.",
          imageSrc:
            "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80",
        },
        {
          id: "t2",
          enabled: true,
          order: 2,
          name: "Anita Gurung",
          position: "Front Office Manager",
          bio: "Ensuring every arrival feels seamless, warm, and memorable.",
          imageSrc:
            "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
        },
        {
          id: "t3",
          enabled: true,
          order: 3,
          name: "Kim Jae-ho",
          position: "Executive Chef",
          bio: "Crafting refined Korean and international cuisine with artistry.",
          imageSrc:
            "https://images.unsplash.com/photo-1583394293214-28ded15ee548?auto=format&fit=crop&w=600&q=80",
        },
        {
          id: "t4",
          enabled: true,
          order: 4,
          name: "Priya Thapa",
          position: "Guest Relations",
          bio: "Personalizing stays with thoughtful touches and local insight.",
          imageSrc:
            "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
        },
      ],
    },
    awards: {
      eyebrow: "Recognition",
      title: "Awards & Achievements",
      items: [
        {
          id: "a1",
          enabled: true,
          order: 1,
          year: "2004",
          title: "Foundation",
          description: "Hotel Thamel Park opens in the heart of Thamel.",
        },
        {
          id: "a2",
          enabled: true,
          order: 2,
          year: "2012",
          title: "Spa Excellence",
          description: "Premium wellness center and spa facilities introduced.",
        },
        {
          id: "a3",
          enabled: true,
          order: 3,
          year: "2018",
          title: "Sky Lounge Acclaim",
          description: "Rooftop restaurant and bar opens to international praise.",
        },
        {
          id: "a4",
          enabled: true,
          order: 4,
          year: "2024",
          title: "Luxury Renovation",
          description: "Complete refinement across guest rooms and public spaces.",
        },
      ],
    },
    testimonials: {
      eyebrow: "Guest Voices",
      title: "What Our Guests Say",
      description: "Discerning travelers from around the world share their experiences.",
      items: [
        {
          id: "r1",
          enabled: true,
          order: 1,
          name: "Elena Richardson",
          country: "United Kingdom",
          review:
            "An absolutely exceptional stay. The attention to detail, the spa experience, and the Korean restaurant exceeded every expectation.",
          rating: 5,
          imageSrc:
            "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
        },
        {
          id: "r2",
          enabled: true,
          order: 2,
          name: "James Nakamura",
          country: "Japan",
          review:
            "The Sky Lounge at sunset is unforgettable. Impeccable service throughout our stay — truly world-class hospitality.",
          rating: 5,
          imageSrc:
            "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
        },
        {
          id: "r3",
          enabled: true,
          order: 3,
          name: "Sophie Laurent",
          country: "France",
          review:
            "From the moment we arrived, every detail was perfect. The family room was spacious and elegant.",
          rating: 5,
          imageSrc:
            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",
        },
      ],
    },
    galleryPreview: {
      eyebrow: "Visual Journey",
      title: "Moments of Elegance",
      ctaText: "View Full Gallery",
      ctaHref: "/gallery",
      images: [
        {
          id: "g1",
          src: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
          alt: "Hotel exterior elegance",
        },
        {
          id: "g2",
          src: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80",
          alt: "Luxury bedroom",
        },
        {
          id: "g3",
          src: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80",
          alt: "Hotel lounge",
        },
        {
          id: "g4",
          src: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
          alt: "Spa experience",
        },
      ],
    },
    cta: {
      title: "Experience Luxury Hospitality in Kathmandu",
      description: "Begin your journey with Hotel Thamel Park & Spa — refined comfort awaits.",
      primaryText: "Book Your Stay",
      primaryHref: "/book",
      secondaryText: "Contact Us",
      secondaryHref: "/contact",
      backgroundImage:
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=2000&q=80",
    },
    seo: {
      title: "About | Hotel Thamel Park & Spa",
      description:
        "Discover the story, philosophy, and luxury hospitality of Hotel Thamel Park & Spa in Thamel, Kathmandu.",
      canonical: "/about",
      ogImage:
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      keywords:
        "about hotel thamel park, luxury hotel kathmandu, boutique hotel thamel, hotel story nepal",
    },
  },
  reviews: [
    {
      id: "1",
      name: "Elena Richardson",
      country: "United Kingdom",
      rating: 5,
      review:
        "An absolutely exceptional stay. The attention to detail, the spa experience, and the Korean restaurant exceeded every expectation.",
    },
    {
      id: "2",
      name: "James Nakamura",
      country: "Japan",
      rating: 5,
      review:
        "The Sky Lounge at sunset is unforgettable. Impeccable service throughout our stay — truly world-class hospitality.",
    },
    {
      id: "3",
      name: "Sophie Laurent",
      country: "France",
      rating: 5,
      review:
        "From the moment we arrived, every detail was perfect. The family room was spacious and elegant.",
    },
  ],
  gallery: [
    {
      id: "1",
      src: "/media/events/ballroom.jpg",
      title: "Grand Ballroom",
      description: "Timeless celebrations in grandeur",
      category: "Meetings",
      type: "image",
      alt: "Grand ballroom at Hotel Thamel Park",
      active: true,
      showOnHome: true,
      order: 0,
    },
    {
      id: "2",
      src: "/media/dining/skyz-lounge.jpg",
      title: "Rooftop Events",
      description: "Evenings above the Kathmandu skyline",
      category: "Rooftop",
      type: "image",
      alt: "Rooftop evening lounge",
      active: true,
      showOnHome: true,
      order: 1,
    },
    {
      id: "3",
      src: "/media/events/conference.jpg",
      title: "Conferences",
      description: "Precision spaces for business excellence",
      category: "Conference",
      type: "image",
      alt: "Conference boardroom",
      active: true,
      showOnHome: true,
      order: 2,
    },
    {
      id: "4",
      src: "/media/events/wedding.jpg",
      title: "Weddings",
      description: "Sacred vows with Himalayan views",
      category: "Wedding",
      type: "image",
      alt: "Wedding celebration venue",
      active: true,
      showOnHome: true,
      order: 3,
    },
    {
      id: "5",
      src: "/media/dining/korean-restaurant.jpg",
      title: "Private Dining",
      description: "Intimate culinary experiences",
      category: "Restaurant",
      type: "image",
      alt: "Private dining room",
      active: true,
      showOnHome: true,
      order: 4,
    },
    {
      id: "6",
      src: "/media/rooms/super-deluxe.jpg",
      title: "Suite Living",
      description: "Refined comfort with mountain vistas",
      category: "Rooms",
      type: "image",
      alt: "Luxury suite living room",
      active: true,
      showOnHome: true,
      order: 5,
    },
    {
      id: "7",
      src: "/media/spa/wellness.jpg",
      title: "Spa Sanctuary",
      description: "Restore body, mind, and spirit",
      category: "Spa",
      type: "image",
      alt: "Spa wellness haven",
      active: true,
      showOnHome: false,
      order: 6,
    },
    {
      id: "8",
      src: "/media/gallery/01.jpg",
      title: "Hotel Arrival",
      description: "A warm welcome in the heart of Thamel",
      category: "Lobby",
      type: "image",
      alt: "Hotel lobby arrival",
      active: true,
      showOnHome: false,
      order: 7,
    },
    {
      id: "9",
      src: "/media/gallery/02.jpg",
      title: "Garden Ambience",
      description: "Serene outdoor hospitality",
      category: "Garden",
      type: "image",
      alt: "Hotel garden sanctuary",
      active: true,
      showOnHome: false,
      order: 8,
    },
  ],
  galleryCategories: [
    { id: "cat-rooms", name: "Rooms", enabled: true, order: 0 },
    { id: "cat-restaurant", name: "Restaurant", enabled: true, order: 1 },
    { id: "cat-sky", name: "Sky Lounge", enabled: true, order: 2 },
    { id: "cat-spa", name: "Spa", enabled: true, order: 3 },
    { id: "cat-meetings", name: "Meetings", enabled: true, order: 4 },
    { id: "cat-conference", name: "Conference", enabled: true, order: 5 },
    { id: "cat-wedding", name: "Wedding", enabled: true, order: 6 },
    { id: "cat-lobby", name: "Lobby", enabled: true, order: 7 },
    { id: "cat-facilities", name: "Facilities", enabled: true, order: 8 },
    { id: "cat-garden", name: "Garden", enabled: true, order: 9 },
    { id: "cat-rooftop", name: "Rooftop", enabled: true, order: 10 },
  ],
  gallerySection: {
    enabled: true,
    eyebrow: "VISUAL JOURNEY",
    title: "MOMENTS OF ELEGANCE",
    description: "Discover the artistry of luxury hospitality captured across our world.",
    ctaText: "VIEW FULL GALLERY",
    ctaHref: routes.gallery,
    ctaVisible: true,
    homeImageLimit: 6,
    showMist: true,
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    borderColor: "#C5A05988",
    cardRadiusPx: 18,
    gridGapPx: 20,
    overlayOpacity: 0.55,
  },
  contact: {
    eyebrow: "Get in Touch",
    title: "Begin Your Luxury Journey",
    description:
      "Whether you seek a reservation, spa appointment, or bespoke arrangement, our concierge team is dedicated to exceeding your expectations.",
    frontDesk: "24 Hours, 7 Days",
    mapEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.234567890123!2d85.3105!3d27.7172!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sThamel%2C%20Kathmandu!5e0!3m2!1sen!2snp!4v1234567890",
    workingHours: "Front Desk: 24/7 | Restaurant: 7:00 AM – 11:00 PM | Spa: 9:00 AM – 9:00 PM",
  },
  galleryPage: {
    hero: {
      title: "Gallery",
      subtitle: "Visual Journey",
      description:
        "A curated collection of moments that define luxury hospitality at Hotel Thamel Park.",
      imageSrc: "/media/gallery/01.jpg",
      media: {
        type: "image",
        imageSrc: "/media/gallery/01.jpg",
        videoSrc: "",
        poster: "",
        alt: "Hotel Thamel Park gallery",
        caption: "",
      },
    },
    seo: {
      title: "Gallery | Hotel Thamel Park",
      description:
        "Explore luxury rooms, spa, dining, weddings, and hotel moments at Hotel Thamel Park, Kathmandu.",
      canonical: "/gallery",
      ogImage: "/media/gallery/01.jpg",
      keywords: "hotel gallery kathmandu, luxury hotel photos, thamel park gallery",
    },
    eyebrow: "VISUAL JOURNEY",
    title: "MOMENTS OF ELEGANCE",
    description: "Discover the artistry of luxury hospitality captured across our world.",
    showFilters: true,
    gridColumns: 3,
    goldColor: "#C5A059",
    headingColor: "#062C24",
    bodyColor: "#5A635C",
    borderColor: "#C5A05988",
    backgroundTop: "#F9F6EF",
    backgroundBottom: "#E8F0E9",
  },
  roomsPage: {
    seo: {
      title: "Rooms & Suites | Hotel Thamel Park",
      description: "Luxury accommodations in Thamel — Super Deluxe, Family Room, and more.",
    },
  },
  contactPage: {
    hero: {
      title: "CONTACT US",
      subtitle: "Luxury Hospitality Begins Here",
      description:
        "We're here to help you plan unforgettable stays, events, dining experiences, wellness retreats, and special occasions.",
      imageSrc:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2000&q=80",
      breadcrumbHome: "Home",
      breadcrumbCurrent: "Contact",
      overlayOpacity: 0.45,
    },
    cards: [
      {
        id: "addr",
        enabled: true,
        order: 1,
        icon: "map-pin",
        title: "Hotel Address",
        value: "Thamel, Kathmandu 44600, Nepal",
        description: "In the heart of Kathmandu’s vibrant cultural district.",
        href: "https://maps.google.com/?q=Thamel+Kathmandu",
      },
      {
        id: "phone",
        enabled: true,
        order: 2,
        icon: "phone",
        title: "Phone",
        value: "+977-1-4412345",
        description: "Speak directly with our reservations team.",
        href: "tel:+97714412345",
      },
      {
        id: "email",
        enabled: true,
        order: 3,
        icon: "mail",
        title: "Email",
        value: "reservations@hotelthamelpark.com",
        description: "We respond to every enquiry with care.",
        href: "mailto:reservations@hotelthamelpark.com",
      },
      {
        id: "hours",
        enabled: true,
        order: 4,
        icon: "clock",
        title: "Reception Hours",
        value: "24 Hours / 7 Days",
        description: "Our front desk is always available for you.",
        href: "",
      },
      {
        id: "whatsapp",
        enabled: true,
        order: 5,
        icon: "message-circle",
        title: "WhatsApp",
        value: "+977-9800000000",
        description: "Message us for instant guest assistance.",
        href: "https://wa.me/9779800000000",
      },
    ],
    form: {
      title: "Booking & Enquiry",
      description:
        "Share your travel plans and preferences — our concierge team will craft a tailored response.",
      submitLabel: "SEND ENQUIRY",
      successTitle: "Enquiry Received",
      successMessage:
        "Thank you for contacting Hotel Thamel Park. A confirmation has been sent to your email, and our team will respond shortly.",
      consentText:
        "I agree to the processing of my personal data for the purpose of this enquiry.",
      bookingTypes: [
        "General Inquiry",
        "Room Booking",
        "Restaurant Reservation",
        "Spa & Wellness",
        "Wedding",
        "Conference",
        "Corporate Meeting",
        "Private Event",
        "Airport Transfer",
        "Travel Desk",
        "Tour Package",
        "Sightseeing",
        "Special Celebration",
        "Other",
      ],
    },
    whyContact: {
      eyebrow: "Why Reach Out",
      title: "Why Contact Us",
      description: "Discerning guests trust our team for seamless, personalized hospitality.",
      items: [
        {
          id: "w1",
          enabled: true,
          order: 1,
          icon: "headset",
          title: "24/7 Guest Support",
          description: "Round-the-clock assistance for reservations, arrivals, and special requests.",
        },
        {
          id: "w2",
          enabled: true,
          order: 2,
          icon: "sparkles",
          title: "Luxury Hospitality",
          description: "Refined service standards inspired by the world’s finest hotels.",
        },
        {
          id: "w3",
          enabled: true,
          order: 3,
          icon: "zap",
          title: "Instant Booking Assistance",
          description: "Fast confirmation for rooms, dining, spa, and private events.",
        },
        {
          id: "w4",
          enabled: true,
          order: 4,
          icon: "heart",
          title: "Personalized Experiences",
          description: "Bespoke itineraries, celebrations, and wellness journeys crafted for you.",
        },
      ],
    },
    location: {
      eyebrow: "Find Us",
      title: "Hotel Location",
      description: "Ideally situated in Thamel — steps from culture, cuisine, and Kathmandu’s landmarks.",
      mapEmbedUrl:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.234567890123!2d85.3105!3d27.7172!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sThamel%2C%20Kathmandu!5e0!3m2!1sen!2snp!4v1234567890",
      mapsDirectionsUrl: "https://www.google.com/maps/dir/?api=1&destination=Thamel,Kathmandu",
      nearbyTitle: "Nearby Attractions",
      nearby: [
        { id: "n1", title: "Thamel Market", distance: "2 min walk" },
        { id: "n2", title: "Garden of Dreams", distance: "8 min walk" },
        { id: "n3", title: "Kathmandu Durbar Square", distance: "15 min" },
        { id: "n4", title: "Tribhuvan International Airport", distance: "25–35 min" },
      ],
    },
    business: {
      eyebrow: "Essential Details",
      title: "Business Information",
      left: [
        { label: "Check-in", value: "From 2:00 PM" },
        { label: "Check-out", value: "Until 12:00 PM" },
        { label: "Reception", value: "24 Hours / 7 Days" },
        { label: "Reservations", value: "6:00 AM – 11:00 PM" },
      ],
      right: [
        { label: "Restaurant Hours", value: "7:00 AM – 11:00 PM" },
        { label: "Spa Hours", value: "9:00 AM – 9:00 PM" },
        { label: "Airport Distance", value: "Approx. 7 km" },
        { label: "City Centre Distance", value: "In the heart of Thamel" },
      ],
    },
    faq: {
      eyebrow: "Helpful Answers",
      title: "Frequently Asked Questions",
      items: [
        {
          id: "f1",
          enabled: true,
          order: 1,
          question: "How can I reserve a room?",
          answer:
            "Submit an enquiry below, call our reservations desk, or use Book Now. Our team will confirm availability and rates promptly.",
        },
        {
          id: "f2",
          enabled: true,
          order: 2,
          question: "Can I organize weddings at the hotel?",
          answer:
            "Yes. We host intimate ceremonies and grand celebrations with dedicated event planners, catering, and elegant venues.",
        },
        {
          id: "f3",
          enabled: true,
          order: 3,
          question: "Is airport pickup available?",
          answer:
            "Airport transfers can be arranged on request. Select Airport Transfer in the booking type or mention it in your message.",
        },
        {
          id: "f4",
          enabled: true,
          order: 4,
          question: "What is the cancellation policy?",
          answer:
            "Standard cancellations made 48 hours or more before arrival typically receive a full refund. Special rates may differ — see our Legal page for details.",
        },
        {
          id: "f5",
          enabled: true,
          order: 5,
          question: "How do I book a restaurant table?",
          answer:
            "Choose Restaurant Reservation as the booking type, or contact us by phone/WhatsApp for same-day dining requests.",
        },
        {
          id: "f6",
          enabled: true,
          order: 6,
          question: "How do I book a spa treatment?",
          answer:
            "Select Spa & Wellness in the enquiry form or call reception. Advance booking is recommended for peak hours.",
        },
      ],
    },
    cta: {
      title: "Ready to Experience Luxury?",
      description: "Begin your journey with Hotel Thamel Park — refined comfort awaits in Kathmandu.",
      primaryText: "Book Your Stay",
      primaryHref: "/book",
      secondaryText: "Call Us",
      secondaryHref: "tel:+97714412345",
      backgroundImage:
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=2000&q=80",
    },
    phone: "+977-1-4412345",
    email: "reservations@hotelthamelpark.com",
    whatsapp: "+9779800000000",
    address: "Thamel, Kathmandu 44600, Nepal",
    seo: {
      title: "Contact | Hotel Thamel Park",
      description:
        "Contact Hotel Thamel Park for room bookings, spa, dining, weddings, and concierge assistance in Thamel, Kathmandu.",
      canonical: "/contact",
      ogImage:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      keywords:
        "contact hotel thamel park, book hotel kathmandu, spa reservation thamel, wedding venue kathmandu",
    },
  },
  seo: {
    title: "Hotel Thamel Park | Luxury Hotel in Thamel, Kathmandu",
    description:
      "Experience ultra-luxury hospitality at Hotel Thamel Park — premium rooms, fine dining, spa wellness, and authentic Nepalese warmth in the heart of Thamel, Kathmandu.",
    keywords:
      "luxury hotel Kathmandu, boutique hotel Thamel, Hotel Thamel Park, spa hotel Kathmandu, fine dining Kathmandu",
    ogImage: "/media/hero/hero-background.png",
    favicon: "/favicon.ico",
    googleAnalytics: "",
    googleTagManager: "",
    robotsAllow: true,
  },
  theme: {
    primary: "#244736",
    secondary: "#183426",
    accent: "#C99A4A",
    champagne: "#D8B46A",
    background: "#F8F5EE",
    borderRadius: "0.75rem",
    fontDisplay: "Cinzel, serif",
    fontBody: "Jost, sans-serif",
    animationSpeed: "slow",
    headerStyle: "glass",
    footerStyle: "gradient",
  },
  settings: {
    bookingEmail: "reservations@hotelthamelpark.com",
  },
  footer: {
    logoSrc: "/media/logo/hotel-logo.png?v=transparent",
    brandName: "HOTEL THAMEL PARK",
    description:
      "Experience timeless elegance, refined hospitality and exceptional comfort in the heart of Kathmandu.",
    tagline: "Where Nepalese warmth meets international luxury.",
    quickLinks: [
      { label: "Overview", href: routes.home },
      { label: "Rooms", href: routes.rooms },
      { label: "Dining", href: routes.dining },
      { label: "Spa & Wellness", href: routes.spa },
      { label: "Gallery", href: routes.gallery },
      { label: "About Us", href: routes.about },
      { label: "Contact Us", href: routes.contact },
    ],
    contact: {
      phone: "+977 1-4412345",
      email: "info@hotelthamelpark.com",
      location: "Thamel, Kathmandu, Nepal",
      frontDesk: "24/7 Front Desk Assistance",
    },
    newsletter: {
      heading: "Stay Connected",
      description: "Subscribe to get special offers, exclusive deals and updates.",
      buttonText: "Subscribe",
      placeholder: "Your email address",
    },
    newsletterText: "Subscribe for exclusive offers and luxury experiences.",
    galleryPreview: [],
    showPayments: true,
    paymentLabel: "Secure Payments",
    enabledPayments: [],
    paymentLogos: [
      { id: "pay1", src: "/media/payments/01-visa.png?v=official3" },
      { id: "pay2", src: "/media/payments/02-mastercard.png?v=official3" },
      { id: "pay3", src: "/media/payments/03-unionpay.png?v=official3" },
      { id: "pay4", src: "/media/payments/04-alipay.png?v=official3" },
      { id: "pay5", src: "/media/payments/05-upi.png?v=official3" },
      { id: "pay6", src: "/media/payments/06-esewa.png?v=official3" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/legal#privacy" },
      { label: "Terms & Conditions", href: "/legal#terms" },
      { label: "Cancellation Policy", href: "/legal#cancellation" },
      { label: "Cookie Settings", href: "/legal#cookies" },
      { label: "Sitemap", href: "/legal#sitemap" },
    ],
    showMountains: true,
    copyrightText: "Hotel Thamel Park. All Rights Reserved.",
    developerLabel: "Developed By The Global Orbit",
    developerUrl: "https://theglobalorbit.com/",
    social: {
      facebook: "https://facebook.com/hotelthamelpark",
      instagram: "https://instagram.com/hotelthamelpark",
      tripadvisor: "https://www.tripadvisor.com/",
      googleReviews: "https://www.google.com/maps",
      facebookIcon: "",
      instagramIcon: "",
      tripadvisorIcon: "",
      googleReviewsIcon: "",
    },
    colors: {
      topBackground: "#14352C",
      bottomBackground: "#0F2820",
      gold: "#D4AF37",
      text: "#F8F5EE",
    },
    spacing: {
      sectionPaddingY: 96,
    },
  },
  mediaLibrary: [],
};
