import { routes } from "@/lib/navigation";
import type {
  HeroBuilderSettings,
  HeroButtonStyle,
  HeroTextStyle,
} from "./hero-builder-types";

const baseText = (overrides: Partial<HeroTextStyle>): HeroTextStyle => ({
  fontFamily: "var(--font-display)",
  fontWeight: 500,
  fontSize: "1rem",
  mobileFontSize: "0.875rem",
  tabletFontSize: "1rem",
  desktopFontSize: "1.125rem",
  color: "#184D3D",
  gradient: "",
  letterSpacing: "0.05em",
  lineHeight: "1.6",
  alignment: "left",
  textShadow: "none",
  animation: "fade",
  ...overrides,
});

const baseButton = (overrides: Partial<HeroButtonStyle>): HeroButtonStyle => ({
  ...baseText({ fontSize: "0.75rem", letterSpacing: "0.18em", color: "#FFFFFF" }),
  text: "Discover More",
  href: "/#overview",
  visible: true,
  icon: "chevron-right",
  iconPosition: "right",
  backgroundColor: "#184D3D",
  backgroundGradient: "",
  borderColor: "transparent",
  borderRadius: "9999px",
  shadow: "0 8px 32px rgba(24, 77, 61, 0.25)",
  hoverAnimation: "scale",
  size: "lg",
  padding: "1rem 1.75rem",
  ...overrides,
});

export const defaultHeroBuilder: HeroBuilderSettings = {
  layout: "premium",
  type: "premium",
  mediaMode: "none",
  previousMedia: { imageSrc: "", videoSrc: "" },
  showTitle: true,
  welcomeText: "LUXURY • HOSPITALITY • MEMORIES",
  title: "EXPERIENCE LUXURY",
  subtitle: "IN THE HEART OF KATHMANDU",
  description:
    "Where timeless elegance meets warm Nepali hospitality.\nYour perfect stay, every single time.",
  videoSrc: "",
  imageSrc: "/media/hero/hero-background.png",
  poster: "",
  overlayOpacity: 0.4,
  overlayColor: "#0E1F16",
  height: "screen",
  animation: "both",
  showBookingBar: true,
  showScrollIndicator: false,
  primaryButton: baseButton({
    text: "EXPLORE HOTEL",
    href: "/#overview",
    visible: true,
    color: "#F6ECD7",
    backgroundColor: "transparent",
    backgroundGradient: "",
    borderColor: "#C9A44C",
    borderRadius: "9999px",
    shadow: "none",
  }),
  secondaryButton: baseButton({
    text: "EXPLORE ROOMS",
    href: routes.rooms,
    visible: false,
    color: "#184D3D",
    backgroundColor: "rgba(255,255,255,0.85)",
    borderColor: "#C89A3D",
    backgroundGradient: "",
    shadow: "none",
  }),
  features: [
    {
      id: "feature-location",
      icon: "map-pin",
      title: "PRIME LOCATION",
      description: "Thamel, Kathmandu",
      enabled: true,
    },
    {
      id: "feature-rate",
      icon: "badge-check",
      title: "BEST RATE GUARANTEE",
      description: "Get the best prices",
      enabled: true,
    },
    {
      id: "feature-support",
      icon: "headphones",
      title: "24/7 SUPPORT",
      description: "We are here to help",
      enabled: true,
    },
  ],
  showFeatures: true,
  colors: {
    cream: "#F8F3EA",
    lightCream: "#FDFBF7",
    royalGreen: "#184D3D",
    premiumGold: "#C89A3D",
    softOrange: "#E9A546",
    accent: "#C89A3D",
    green: "#184D3D",
    white: "#FDFBF7",
    dark: "#0F2E24",
    champagne: "#EED8B3",
  },
  image: {
    src: "/media/hero/hero-background.png",
    mobileSrc: "/media/hero/hero-background.png",
    tabletSrc: "/media/hero/hero-background.png",
    desktopSrc: "/media/hero/hero-background.png",
    alt: "Hotel Thamel Park with Himalayan mountain views",
    position: "center 42%",
    scale: 1,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    exposure: 100,
    blur: 0,
    rotate: 0,
    flipX: false,
    flipY: false,
    overlayColor: "transparent",
    gradientOverlay: "radial-gradient(ellipse at 55% 40%, rgba(255,248,230,0.2) 0%, transparent 50%)",
    overlayOpacity: 0.2,
    borderRadius: "0",
    parallax: true,
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "scroll",
    animation: "float",
    preload: true,
  },
  logo: {
    src: "/media/logo/hotel-logo.png",
    width: 120,
    height: 120,
    opacity: 1,
    rotation: 0,
    borderRadius: "0",
    shadow: "none",
    glow: "0 0 40px rgba(200, 154, 61, 0.2)",
    background: "transparent",
    visible: false,
    padding: "0",
    margin: "0",
    positionDesktop: "left",
    positionTablet: "center",
    positionMobile: "center",
  },
  welcomeStyle: baseText({
    fontSize: "0.75rem",
    mobileFontSize: "0.65rem",
    desktopFontSize: "0.8rem",
    letterSpacing: "0.3em",
    color: "#E3C685",
    alignment: "left",
  }),
  titleStyle: baseText({
    fontSize: "2.25rem",
    mobileFontSize: "1.875rem",
    tabletFontSize: "2.5rem",
    desktopFontSize: "2.75rem",
    fontWeight: 500,
    letterSpacing: "0.05em",
    lineHeight: "1.2",
    color: "#FFFFFF",
  }),
  subtitleStyle: baseText({
    fontSize: "2.25rem",
    mobileFontSize: "1.875rem",
    tabletFontSize: "2.5rem",
    desktopFontSize: "2.75rem",
    fontWeight: 500,
    letterSpacing: "0.05em",
    lineHeight: "1.2",
    color: "#D9B45C",
  }),
  descriptionStyle: baseText({
    fontFamily: "var(--font-body)",
    fontSize: "1rem",
    mobileFontSize: "0.9375rem",
    desktopFontSize: "1.0625rem",
    color: "#F1E9DA",
    letterSpacing: "0.02em",
    lineHeight: "1.75",
    fontWeight: 400,
  }),
  bookingBar: {
    enabled: true,
    fixedPosition: false,
    background: "linear-gradient(160deg, #2A5540 0%, #204732 55%, #26503B 100%)",
    borderColor: "rgba(201,164,76,0.45)",
    defaults: {
      guests: "2",
      children: "0",
      rooms: "1",
    },
    glassEffect: true,
    blur: 18,
    shadow: "0 30px 80px rgba(8,20,14,0.45), inset 0 1px 0 rgba(255,255,255,0.08)",
    borderRadius: "20px",
    height: "108px",
    maxWidth: "none",
    padding: "0",
    margin: "0 auto",
    gap: "0",
    buttonText: "CHECK AVAILABILITY",
    buttonGradient: "linear-gradient(180deg, #E4C173 0%, #C9A44C 55%, #B08A34 100%)",
    buttonColor: "#1E4530",
    buttonHeight: "72px",
    buttonWidth: "100%",
    buttonBorderRadius: "14px",
    buttonShadow: "0 18px 45px rgba(190,150,50,0.35)",
    fieldBorderRadius: "12px",
    fieldPadding: "14px 18px",
    labelFontSize: "11px",
    valueFontSize: "17px",
    labelLetterSpacing: "0.16em",
    spacing: "0",
    colors: {
      label: "#E3C685",
      value: "#FFFFFF",
      divider: "rgba(201,164,76,0.3)",
      border: "rgba(201,164,76,0.45)",
      buttonText: "#1E4530",
      buttonGradientFrom: "#E4C173",
      buttonGradientTo: "#B08A34",
    },
    labels: {
      checkIn: "CHECK IN",
      checkOut: "CHECK OUT",
      guests: "GUESTS",
      children: "CHILDREN",
      room: "ROOM",
    },
    icons: {
      checkIn: "calendar",
      checkOut: "calendar",
      guests: "users",
      children: "baby",
      room: "bed-double",
    },
    animations: {
      entrance: true,
      float: true,
      buttonGlow: true,
      hoverGlow: true,
      buttonLift: true,
    },
    responsive: {
      desktopBottom: "24px",
      desktopMaxWidth: "none",
      desktopWidth: "calc(100% - 48px)",
      desktopMinWidth: "0",
      mobileBottom: "16px",
      mobileHorizontalInset: "16px",
      mobileRadius: "20px",
      mobilePadding: "16px",
    },
    fields: {
      checkIn: true,
      checkOut: true,
      guests: true,
      children: true,
      room: true,
    },
  },
  effects: {
    goldenGlow: true,
    creamGlow: true,
    orangeGlow: false,
    greenGlow: false,
    lightRays: false,
    fog: false,
    floatingLeaves: false,
    floatingShapes: false,
    particles: true,
    blur: 0,
    gradient: "radial-gradient(ellipse at 75% 40%, rgba(200, 154, 61, 0.12) 0%, transparent 55%)",
  },
  floating: {
    shapeCount: 4,
    shapeSize: 32,
    rotation: 45,
    speed: 22,
    opacity: 0.25,
    animation: "float",
    randomMovement: true,
  },
  animations: {
    entrance: "fade",
    scrollReveal: true,
    mouseParallax: true,
    transitionDuration: 0.9,
    easing: "0.22, 1, 0.36, 1",
  },
  responsive: {
    desktopPadding: "6rem 2rem 2rem",
    tabletPadding: "5rem 1.5rem 1.5rem",
    mobilePadding: "5.5rem 1.25rem 1.25rem",
    imageSizeDesktop: 580,
    imageSizeTablet: 380,
    imageSizeMobile: 280,
    contentAlignment: "left",
  },
  seo: {
    heroTitle: "Hotel Thamel Park | Luxury in Thamel, Kathmandu",
    metaTitle: "Hotel Thamel Park | Luxury Hotel in Thamel, Kathmandu",
    metaDescription:
      "Experience unparalleled comfort and refined hospitality at Hotel Thamel Park in the heart of Thamel, Kathmandu.",
    ogImage: "/media/hero/hero-background.png",
    twitterImage: "/media/hero/hero-background.png",
    altText: "Hotel Thamel Park luxury property with Himalayan views",
    schemaEnabled: true,
  },
};
