import { routes } from "@/lib/navigation";
import type {
  HeroBuilderSettings,
  HeroButtonStyle,
  HeroTextStyle,
} from "./hero-builder-types";

const baseText = (overrides: Partial<HeroTextStyle>): HeroTextStyle => ({
  fontFamily: "var(--font-display)",
  fontWeight: 500,
  fontSize: "1rem",
  mobileFontSize: "0.875rem",
  tabletFontSize: "1rem",
  desktopFontSize: "1.125rem",
  color: "#184D3D",
  gradient: "",
  letterSpacing: "0.05em",
  lineHeight: "1.6",
  alignment: "left",
  textShadow: "none",
  animation: "fade",
  ...overrides,
});

const baseButton = (overrides: Partial<HeroButtonStyle>): HeroButtonStyle => ({
  ...baseText({ fontSize: "0.75rem", letterSpacing: "0.18em", color: "#FFFFFF" }),
  text: "Discover More",
  href: "/#overview",
  visible: true,
  icon: "chevron-right",
  iconPosition: "right",
  backgroundColor: "#184D3D",
  backgroundGradient: "",
  borderColor: "transparent",
  borderRadius: "9999px",
  shadow: "0 8px 32px rgba(24, 77, 61, 0.25)",
  hoverAnimation: "scale",
  size: "lg",
  padding: "1rem 1.75rem",
  ...overrides,
});

export const defaultHeroBuilder: HeroBuilderSettings = {
  layout: "premium",
  type: "premium",
  showTitle: false,
  welcomeText: "",
  title: "",
  subtitle: "",
  description: "",
  videoSrc: "",
  imageSrc: "/media/hero/hero-background.png",
  poster: "",
  overlayOpacity: 0,
  overlayColor: "#184D3D",
  height: "screen",
  animation: "both",
  showBookingBar: true,
  showScrollIndicator: false,
  primaryButton: baseButton({
    text: "DISCOVER MORE",
    href: "/#overview",
    visible: false,
    backgroundColor: "#184D3D",
  }),
  secondaryButton: baseButton({
    text: "EXPLORE ROOMS",
    href: routes.rooms,
    visible: false,
    color: "#184D3D",
    backgroundColor: "rgba(255,255,255,0.85)",
    borderColor: "#C89A3D",
    backgroundGradient: "",
    shadow: "none",
  }),
  colors: {
    cream: "#F8F3EA",
    lightCream: "#FDFBF7",
    royalGreen: "#184D3D",
    premiumGold: "#C89A3D",
    softOrange: "#E9A546",
    accent: "#C89A3D",
    green: "#184D3D",
    white: "#FDFBF7",
    dark: "#0F2E24",
    champagne: "#EED8B3",
  },
  image: {
    src: "/media/hero/hero-background.png",
    mobileSrc: "/media/hero/hero-background.png",
    tabletSrc: "/media/hero/hero-background.png",
    desktopSrc: "/media/hero/hero-background.png",
    alt: "Hotel Thamel Park & Spa with Himalayan mountain views",
    position: "center",
    scale: 1,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    exposure: 100,
    blur: 0,
    rotate: 0,
    flipX: false,
    flipY: false,
    overlayColor: "transparent",
    gradientOverlay: "radial-gradient(ellipse at 55% 40%, rgba(255,248,230,0.2) 0%, transparent 50%)",
    overlayOpacity: 0.2,
    borderRadius: "0",
    parallax: true,
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "scroll",
    animation: "float",
    preload: true,
  },
  logo: {
    src: "/media/logo/hotel-logo.png",
    width: 120,
    height: 120,
    opacity: 1,
    rotation: 0,
    borderRadius: "0",
    shadow: "none",
    glow: "0 0 40px rgba(200, 154, 61, 0.2)",
    background: "transparent",
    visible: false,
    padding: "0",
    margin: "0",
    positionDesktop: "left",
    positionTablet: "center",
    positionMobile: "center",
  },
  welcomeStyle: baseText({
    fontSize: "0.75rem",
    mobileFontSize: "0.65rem",
    desktopFontSize: "0.8rem",
    letterSpacing: "0.35em",
    color: "#184D3D",
    alignment: "left",
  }),
  titleStyle: baseText({
    fontSize: "2.5rem",
    mobileFontSize: "1.75rem",
    tabletFontSize: "2rem",
    desktopFontSize: "2.75rem",
    fontWeight: 500,
    letterSpacing: "0.12em",
    lineHeight: "1.15",
    color: "#184D3D",
  }),
  subtitleStyle: baseText({
    fontSize: "0.7rem",
    mobileFontSize: "0.6rem",
    desktopFontSize: "0.75rem",
    letterSpacing: "0.4em",
    color: "#C89A3D",
    fontWeight: 500,
  }),
  descriptionStyle: baseText({
    fontFamily: "var(--font-body)",
    fontSize: "0.95rem",
    mobileFontSize: "0.875rem",
    desktopFontSize: "1rem",
    color: "#4A5E56",
    letterSpacing: "0.02em",
    lineHeight: "1.75",
    fontWeight: 400,
  }),
  bookingBar: {
    enabled: true,
    fixedPosition: false,
    background: "linear-gradient(135deg, rgba(36,71,54,0.94) 0%, rgba(24,52,38,0.92) 50%, rgba(36,71,54,0.9) 100%)",
    glassEffect: true,
    blur: 28,
    shadow: "0 32px 90px rgba(24,56,47,0.12), 0 0 0 1px rgba(255,255,255,0.5), inset 0 1px 0 rgba(255,255,255,0.8)",
    borderRadius: "28px",
    height: "108px",
    maxWidth: "1700px",
    padding: "0",
    margin: "0 auto",
    gap: "0",
    buttonText: "CHECK AVAILABILITY",
    buttonGradient: "linear-gradient(180deg, #D8B25B 0%, #B98B2C 100%)",
    buttonColor: "#FFFFFF",
    buttonHeight: "72px",
    buttonWidth: "100%",
    buttonBorderRadius: "22px",
    buttonShadow: "0 20px 50px rgba(190,150,50,0.35)",
    fieldBorderRadius: "20px",
    fieldPadding: "16px 20px",
    labelFontSize: "11px",
    valueFontSize: "18px",
    labelLetterSpacing: "0.2em",
    spacing: "0",
    colors: {
      label: "#C9A44C",
      value: "#18382F",
      divider: "#C9A44C",
      border: "rgba(255,255,255,0.65)",
      buttonText: "#FFFFFF",
      buttonGradientFrom: "#D8B25B",
      buttonGradientTo: "#B98B2C",
    },
    labels: {
      checkIn: "CHECK IN",
      checkOut: "CHECK OUT",
      guests: "GUESTS",
      children: "CHILDREN",
      room: "ROOMS",
    },
    icons: {
      checkIn: "calendar",
      checkOut: "calendar",
      guests: "users",
      children: "baby",
      room: "bed-double",
    },
    animations: {
      entrance: true,
      float: true,
      buttonGlow: true,
      hoverGlow: true,
      buttonLift: true,
    },
    responsive: {
      desktopBottom: "0px",
      desktopMaxWidth: "1700px",
      desktopWidth: "95%",
      desktopMinWidth: "0",
      mobileBottom: "0px",
      mobileHorizontalInset: "12px",
      mobileRadius: "26px",
      mobilePadding: "16px",
    },
    fields: {
      checkIn: true,
      checkOut: true,
      guests: true,
      children: true,
      room: true,
    },
  },
  effects: {
    goldenGlow: true,
    creamGlow: true,
    orangeGlow: false,
    greenGlow: false,
    lightRays: false,
    fog: false,
    floatingLeaves: false,
    floatingShapes: false,
    particles: true,
    blur: 0,
    gradient: "radial-gradient(ellipse at 75% 40%, rgba(200, 154, 61, 0.12) 0%, transparent 55%)",
  },
  floating: {
    shapeCount: 4,
    shapeSize: 32,
    rotation: 45,
    speed: 22,
    opacity: 0.25,
    animation: "float",
    randomMovement: true,
  },
  animations: {
    entrance: "fade",
    scrollReveal: true,
    mouseParallax: true,
    transitionDuration: 0.9,
    easing: "0.22, 1, 0.36, 1",
  },
  responsive: {
    desktopPadding: "6rem 2rem 2rem",
    tabletPadding: "5rem 1.5rem 1.5rem",
    mobilePadding: "5.5rem 1.25rem 1.25rem",
    imageSizeDesktop: 580,
    imageSizeTablet: 380,
    imageSizeMobile: 280,
    contentAlignment: "left",
  },
  seo: {
    heroTitle: "Hotel Thamel Park & Spa | Luxury in Thamel, Kathmandu",
    metaTitle: "Hotel Thamel Park & Spa | Luxury Hotel in Thamel, Kathmandu",
    metaDescription:
      "Experience unparalleled comfort and refined hospitality at Hotel Thamel Park & Spa in the heart of Thamel, Kathmandu.",
    ogImage: "/media/hero/hero-background.png",
    twitterImage: "/media/hero/hero-background.png",
    altText: "Hotel Thamel Park & Spa luxury property with Himalayan views",
    schemaEnabled: true,
  },
};
